name       : python-imageio
version    : 2.9.0
release    : 4
source     :
    - https://github.com/imageio/imageio/archive/refs/tags/v2.9.0.tar.gz : 6a4bb17127d1af103bf146f8b0bd68ccb647a926002e8a6800c6d7859048661a
license    : BSD-2-Clause
component  : programming.python
summary    : Python library for reading and writing image data
description: |
    Imageio is a Python library that provides an easy interface to read and write a wide range of image data, including animated images, video, volumetric data, and scientific formats.
rundeps    :
    - numpy
    - python-pillow
build      : |
    %python3_setup
install    : |
    %python3_install
