name       : python-imageio
version    : 2.22.4
release    : 7
source     :
    - https://github.com/imageio/imageio/releases/download/v2.22.4/imageio-2.22.4.tar.gz : 0fae027addf02bc89c73a56cc157ad84557f8b8b84aa19b4cb706fefca2d88ff
license    : BSD-2-Clause
component  : programming.python
summary    : Python library for reading and writing image data
description: |
    Imageio is a Python library that provides an easy interface to read and write a wide range of image data, including animated images, video, volumetric data, and scientific formats.
rundeps    :
    - numpy
    - python-pillow
build      : |
    %python3_setup
install    : |
    %python3_install
